# Adds the "Documents -> Google Drive" mirror to an already installed Sheet sync Worker.
#
#   powershell -ExecutionPolicy Bypass -File .\scripts\setup-documents-drive.ps1
#   (or: npm run setup:documents-drive)
#
# Run scripts/setup-sheet-sync.ps1 first. This script:
#   1 folder    picks the Drive folder that receives one .md file per document: paste the URL of a
#               folder in a SHARED DRIVE (recommended), or leave empty to create one in My Drive
#   2 share     shares that folder with the Worker's service account
#   3 deploy    saves GOOGLE_DRIVE_FOLDER_ID as a Worker secret and redeploys the Worker
#   4 sync      runs the first mirror pass and tells you whether Drive accepted the files
#
# Why a Shared Drive: Google gives service accounts no storage quota, so on a personal Google
# account (gmail.com) the service account cannot create files in My Drive and step 4 reports a
# storage-quota error. A Shared Drive (Google Workspace) has no such limit.
#
# Resumable and idempotent: progress is kept in workers/trello-sheet-sync/.setup-state.json.
# Re-run with the same command. -Reset forgets the chosen folder only (not the Sheet sync setup).

param(
  [switch]$Reset,
  [string]$FolderId
)

$ErrorActionPreference = "Stop"
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8; $OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

$RepoRoot = Split-Path -Parent $PSScriptRoot
$WorkerDir = Join-Path $RepoRoot "workers\trello-sheet-sync"
$StatePath = Join-Path $WorkerDir ".setup-state.json"
$DevVarsPath = Join-Path $WorkerDir ".dev.vars"

function Write-Step([string]$Text) { Write-Host "`n== $Text ==" -ForegroundColor Cyan }
function Write-Info([string]$Text) { Write-Host "  $Text" -ForegroundColor DarkGray }

# ---------------------------------------------------------------- helpers -------------------------------------------
function Read-DevVars {
  $vars = [ordered]@{}
  if (Test-Path $DevVarsPath) {
    foreach ($line in Get-Content $DevVarsPath) {
      if ($line -match '^\s*([A-Z0-9_]+)=(.*)$') { $vars[$Matches[1]] = $Matches[2] }
    }
  }
  return $vars
}

function Write-DevVars($vars) {
  $lines = @("# Generated by scripts/setup-sheet-sync.ps1. Gitignored - never commit.")
  foreach ($k in $vars.Keys) { $lines += "$k=$($vars[$k])" }
  Set-Content -Path $DevVarsPath -Value ($lines -join "`n") -NoNewline
}

# Runs a native command with stderr noise tolerated; returns its exit code only.
function Invoke-Native([scriptblock]$Command) {
  $prev = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try { & $Command | Out-Host; return [int]$LASTEXITCODE } finally { $ErrorActionPreference = $prev }
}

# "https://drive.google.com/drive/folders/1AbC...?usp=sharing", ".../u/0/folders/1AbC..." or a bare id -> the id, else $null.
function ConvertTo-DriveFolderId([string]$Text) {
  $t = "$Text".Trim().Trim('"').Trim("'")
  if ($t -match 'folders/([A-Za-z0-9_-]{10,})') { return $Matches[1] }
  if ($t -match '^[A-Za-z0-9_-]{10,}$') { return $t }
  return $null
}

function Add-GcloudToSessionPath {
  foreach ($dir in @(
      (Join-Path $env:LOCALAPPDATA "google-cloud-sdk\google-cloud-sdk\bin"),
      (Join-Path $env:LOCALAPPDATA "Google\Cloud SDK\google-cloud-sdk\bin"),
      (Join-Path ${env:ProgramFiles(x86)} "Google\Cloud SDK\google-cloud-sdk\bin"),
      (Join-Path $env:ProgramFiles "Google\Cloud SDK\google-cloud-sdk\bin"))) {
    if ($dir -and (Test-Path (Join-Path $dir "gcloud.cmd")) -and ($env:Path -notlike "*$dir*")) { $env:Path = "$dir;$env:Path" }
  }
}

function Get-GcloudAccount {
  $prev = $ErrorActionPreference; $ErrorActionPreference = "Continue"
  $out = gcloud auth list --filter="status:ACTIVE" --format="value(account)" 2>$null
  $ErrorActionPreference = $prev
  if ([string]::IsNullOrWhiteSpace($out)) { return $null }
  return "$out".Trim()
}

function Get-HumanAuthHeader {
  $prev = $ErrorActionPreference; $ErrorActionPreference = "Continue"
  $token = gcloud auth print-access-token --account=$script:Account --scopes="https://www.googleapis.com/auth/drive" 2>$null
  $exit = $LASTEXITCODE
  $ErrorActionPreference = $prev
  if ($exit -ne 0 -or [string]::IsNullOrWhiteSpace($token)) {
    throw "gcloud login for $($script:Account) has no Drive access. Run 'gcloud auth login --enable-gdrive-access', then re-run."
  }
  return @{ Authorization = "Bearer $("$token".Trim())" }
}

# Drive answers 403/404/429/5xx for a while after a change: retry, and surface the real response body.
function Invoke-GoogleApiWithRetry {
  param([string]$Label, [scriptblock]$Request, [int]$MaxAttempts = 5, [int]$Delay = 10)
  for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
    try { return & $Request } catch {
      $status = $null; $body = $null
      if ($_.Exception.Response) {
        $status = [int]$_.Exception.Response.StatusCode
        try { $body = (New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())).ReadToEnd() } catch {}
      }
      $retryable = ($status -in 429) -or ($status -ge 500)
      if ($retryable -and $attempt -lt $MaxAttempts) {
        Write-Host "  $Label attempt $attempt/$MaxAttempts -> HTTP $status, retrying in ${Delay}s" -ForegroundColor Yellow
        Start-Sleep -Seconds $Delay
        continue
      }
      if ($body) { throw "$Label failed (HTTP $status): $body" }
      throw
    }
  }
}

function Invoke-Worker([string]$Method, [string]$Path) {
  $vars = Read-DevVars
  return Invoke-RestMethod -Method $Method -Uri ($script:State.workerUrl.TrimEnd('/') + $Path) -Headers @{ "x-sync-secret" = $vars['SYNC_SECRET'] } -TimeoutSec 120
}

# ---------------------------------------------------------------- checks --------------------------------------------
if (-not (Test-Path $StatePath) -or -not (Test-Path $DevVarsPath)) {
  throw "The Sheet sync is not installed yet. Run: npm run setup:sheet-sync"
}
$State = @{}
(Get-Content -Raw $StatePath | ConvertFrom-Json).PSObject.Properties | ForEach-Object { $State[$_.Name] = $_.Value }
function Save-State { $script:State | ConvertTo-Json -Depth 5 | Set-Content -Path $StatePath -Encoding UTF8 }
if (-not $State.workerUrl) { throw "No Worker URL in $StatePath. Finish the Sheet sync setup first: npm run setup:sheet-sync" }
$vars = Read-DevVars
if (-not $vars['GOOGLE_SERVICE_ACCOUNT_EMAIL']) { throw "No service account in $DevVarsPath. Finish the Sheet sync setup first: npm run setup:sheet-sync" }
$saEmail = $vars['GOOGLE_SERVICE_ACCOUNT_EMAIL']

if ($Reset) { $State.Remove('driveFolderId'); $State.Remove('done_docs_folder'); $State.Remove('done_docs_deploy'); Save-State }
if ($FolderId) {
  $parsed = ConvertTo-DriveFolderId $FolderId
  if (-not $parsed) { throw "-FolderId is not a Drive folder URL or id: $FolderId" }
  $State.driveFolderId = $parsed
  Save-State
}

Add-GcloudToSessionPath
if (-not (Get-Command gcloud -ErrorAction SilentlyContinue)) { throw "gcloud not found. Run npm run setup:sheet-sync once (it installs it), then re-run this script." }
$script:Account = Get-GcloudAccount
if (-not $script:Account) {
  if ((Invoke-Native { gcloud auth login --enable-gdrive-access }) -ne 0) { throw "gcloud login failed" }
  $script:Account = Get-GcloudAccount
}
Write-Info "gcloud account: $($script:Account)"

# ---------------------------------------------------------------- 1 + 2 folder, share --------------------------------
Write-Step "1/4 Drive folder for the documents"
if (-not $State.driveFolderId) {
  Write-Info "Paste the URL of a folder in a Shared Drive (recommended), or press Enter to create one in My Drive."
  Write-Info "(On a personal Google account, My Drive makes Google refuse the files: see the note at the top of this script.)"
  while ($true) {
    $typed = Read-Host "  Folder URL or id [Enter = create in My Drive]"
    if ([string]::IsNullOrWhiteSpace($typed)) {
      $name = if ($State.boardName) { "Trello - $($State.boardName) - Documents" } else { "Trello - Documents" }
      $body = @{ name = $name; mimeType = "application/vnd.google-apps.folder" } | ConvertTo-Json
      $created = Invoke-GoogleApiWithRetry -Label "Create folder" -Request {
        Invoke-RestMethod -Method Post -Uri "https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&fields=id" -Headers (Get-HumanAuthHeader) -ContentType "application/json; charset=utf-8" -Body $body
      }
      $State.driveFolderId = "$($created.id)"
      break
    }
    $parsed = ConvertTo-DriveFolderId $typed
    if ($parsed) { $State.driveFolderId = $parsed; break }
    Write-Host "  That is not a Drive folder URL (expected https://drive.google.com/drive/folders/...). Try again, or press Enter." -ForegroundColor Yellow
  }
  Save-State
}
Write-Info "Folder: https://drive.google.com/drive/folders/$($State.driveFolderId)"

Write-Step "2/4 Sharing the folder with the service account"
$perm = @{ role = "writer"; type = "user"; emailAddress = $saEmail } | ConvertTo-Json
Invoke-GoogleApiWithRetry -Label "Share folder" -Request {
  Invoke-RestMethod -Method Post -Uri "https://www.googleapis.com/drive/v3/files/$($State.driveFolderId)/permissions?sendNotificationEmail=false&supportsAllDrives=true" -Headers (Get-HumanAuthHeader) -ContentType "application/json; charset=utf-8" -Body $perm
} | Out-Null
Write-Info "Shared with $saEmail"

# ---------------------------------------------------------------- 3 deploy ------------------------------------------
Write-Step "3/4 Saving the secret and redeploying the Worker"
$vars = Read-DevVars
$vars['GOOGLE_DRIVE_FOLDER_ID'] = $State.driveFolderId
Write-DevVars $vars
$bulk = Join-Path $env:TEMP ("secrets-" + [guid]::NewGuid().ToString("N") + ".json")
Push-Location $WorkerDir
try {
  # Deploy first: a Worker that does not know the secret yet just ignores it.
  if ((Invoke-Native { npx --yes wrangler deploy }) -ne 0) { throw "wrangler deploy failed" }
  (@{ GOOGLE_DRIVE_FOLDER_ID = $State.driveFolderId } | ConvertTo-Json) | Set-Content -Path $bulk -Encoding UTF8
  if ((Invoke-Native { npx --yes wrangler secret bulk $bulk }) -ne 0) { throw "wrangler secret bulk failed" }
} finally {
  Remove-Item $bulk -Force -ErrorAction SilentlyContinue
  Pop-Location
}

# ---------------------------------------------------------------- 4 first sync --------------------------------------
Write-Step "4/4 First mirror pass"
Start-Sleep -Seconds 5
$result = Invoke-GoogleApiWithRetry -Label "Documents sync" -MaxAttempts 4 -Delay 8 -Request { Invoke-Worker "Post" "/documents/sync" }
if ($result.error) {
  Write-Host "  The Worker could not write to Drive:" -ForegroundColor Red
  Write-Host "  $($result.error)" -ForegroundColor Red
  Write-Host "  Fix it, then run the same command again (it resumes, nothing is lost):" -ForegroundColor Yellow
  Write-Host "    npm run setup:documents-drive" -ForegroundColor Yellow
  exit 1
}
Write-Host ("  {0} document(s): {1} created, {2} updated, {3} unchanged, {4} removed" -f $result.documents, $result.created, $result.updated, $result.unchanged, $result.trashed) -ForegroundColor Green
Write-Host "`nDone. Every document saved in Trello now appears as a .md file in:" -ForegroundColor Green
Write-Host "  https://drive.google.com/drive/folders/$($State.driveFolderId)" -ForegroundColor Green
